/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Invoices {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  id: string;
  paid_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  age: number | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  invoices: Invoices;
  users: Users;
}
